name: Deploy to Oracle Instance

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Load code from GitHub repository
        uses: actions/checkout@v4

      - name: Copy next.config.ts
        run: echo "${{ secrets.NEXT_CONFIG_TS }}" > ./next.config.ts

      - name: Copy .env
        run: echo "${{ secrets.ENV }}" > ./.env

      - name: Build Docker image
        run: sudo docker build -t gdgoctuk/gdgoctuk-frontend .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: sudo docker push gdgoctuk/gdgoctuk-frontend

      - name: SSH into Oracle VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            sudo docker pull gdgoctuk/gdgoctuk-frontend
            sudo docker stop frontend || true
            sudo docker rm frontend || true
            sudo docker run -d \
              --name frontend \
              -p 3000:3000 \
              --restart=always \
              gdgoctuk/gdgoctuk-frontend
            sudo docker image prune -f
